name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true


[[routes]]
pattern = "inputbugwildcard.cloudproxyip.my.id.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "inputbugwildcard.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "subapi.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.loss.cloudproxyip.my.id"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.loss.cloudproxyip.my.id"
custom_domain = true
