name = "cf" # todo
main = "js/_worker.js"
compatibility_date = "2024-05-26"


[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true



[[routes]]
pattern = "molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "live.iflix.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "ads.ruangguru.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "io.ruangguru.com.molen.cepu.us.kg"
custom_domain = true
[[routes]]
pattern = "api.midtrans.com.molen.cepu.us.kg"
custom_domain = true
